apiVersion: ec2.aws.crossplane.io/v1beta1
kind: VPC
metadata:
  name: knoldus-crossplane-vpc
  namespace: crossplane
spec:
  forProvider:
    cidrBlock: 10.100.0.0/16
    enableDnsSupport: true
    enableDnsHostNames: true
  reclaimPolicy: Delete
  providerConfigRef:
    name: crossplane-provider-config
  providerRef:
    name: crossplane-provider-config
